name: Build, Push and Deploy Logs Service

on:
  push:
    branches:
      - deploy # branch riêng cho logs-service

jobs:
  build-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Logs Service image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: norman1910/alpha-code-logs-service:latest
          cache-from: type=registry,ref=norman1910/alpha-code-logs-service:latest
          cache-to: type=inline

  deploy-logs:
    needs: build-logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Logs Service with podman-compose via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << EOF
            set -e
            cd /home/norman/SEP/alpha-code-logs-service
            echo "${{ secrets.SSH_PASS }}" | sudo -S podman-compose down
            echo "${{ secrets.SSH_PASS }}" | sudo -S podman-compose pull
            echo "${{ secrets.SSH_PASS }}" | sudo -S podman-compose up -d
          EOF
